### ISSUE TITLE
[ROS2 Port] [Meta] Port to ROS2 task

### ISSUE THREAD

**Issue by jubeira** [ros2/rosbridge_suite#1]
# Porting rosbridge_suite to ROS2
This is a meta-ticket to describe the tasks to be done and their progress.

## Packages
- [x] rosapi
  - [x] rosapi python package and node
  - [x] messages and services
- [x] rosbridge_library
  - [x] rosbridge_library
  - [x] capabilities
  - [x] internal
  - [x] util
- [ ] rosbridge_server 
  - [ ] rosbridge_server
  - [ ] scripts
  - [ ] launchfiles
- [ ] misc
  - [x] Catkin --> Ament (https://github.com/ros2/rosbridge_suite/tree/ros2_ament_cmake)
  - [ ] Messages / services definitions
